### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by lyh16** [axyyu/notion-clear-trash#2]
Until the time that Notion.so supports official API, many people will rely on your code to automate the deletion of their trashed blocks. Thankfully, you've merged a pull request from me before, but I think it would be great if you could keep everyone who would like to add on to or fork from your work safe by adding a license to your work(ex. MIT License, etc.).

https://choosealicense.com/no-permission/

**Comment by axyyu** [comment]
Good point, I'll add the MIT license soon.
