### ISSUE TITLE
Not found for url

### ISSUE THREAD

**Issue by ghost** [axyyu/notion-clear-trash#8]
![image](https://user-images.githubusercontent.com/10127702/103627002-4ab66980-4f3d-11eb-880f-37dd0800221c.png)

**Comment by binvius** [comment]
We're receiving the same error on all of our boxes.

**Comment by fharper** [comment]
I had the same error, probably because Notion changed their API endpoint.

**Comment by ghost** [comment]
Solved it in my fork: https://github.com/mariusraht1/notion-clear-trash
